export { default as ConfettiAnimation } from './confetti.json'
export { default as LiveAnimation } from './live.json'
export { default as MobileAnimation } from './mobile.json'
export { default as ServerErrorAnimation } from './server-error.json'
export { default as ErrorAnimation } from './error.json'
export { default as ClappingAnimation } from './clapping.json'
export { default as SuccessTickAnimation } from './success-tick.json'
