export const UPDATE_AUTH_STATUS = 'auth/UPDATE_AUTH_STATUS'
export const HANDLE_SEND_OTP = 'auth/HANDLE_SEND_OTP'
export const HANDLE_RESEND_OTP = 'auth/HANDLE_RESEND_OTP'
export const HANDLE_VERIFY_OTP = 'auth/HANDLE_VERIFY_OTP'
export const HANDLE_SECURITY_PIN_SEND_OTP = 'auth/HANDLE_SECURITY_PIN_SEND_OTP'
export const HANDLE_SECURITY_PIN_VERIFY = 'auth/HANDLE_SECURITY_PIN_VERIFY'
export const HANDLE_SECURITY_PIN_RESEND_OTP =
  'auth/HANDLE_SECURITY_PIN_RESEND_OTP'
export const HANDLE_SECURITY_PIN_VERIFY_OTP =
  'auth/HANDLE_SECURITY_PIN_VERIFY_OTP'
export const HANDLE_LOGOUT = 'auth/HANDLE_LOGOUT'
export const RESET_AUTH_STATE = 'auth/RESET_AUTH_STATE'
export const RESET_AUTH_STATUS = 'auth/RESET_AUTH_STATUS'
