export const UPDATE_PAYMENT_STATUS = 'payment/UPDATE_PAYMENT_STATUS'
export const HANDLE_PAYMENT_INTENT = 'payment/HANDLE_PAYMENT_INTENT'
export const HANDLE_CONFIRM_PAYMENT = 'payment/HANDLE_CONFIRM_PAYMENT'
export const HANDLE_RETRIEVE_PAYMENT_INTENT =
  'payment/HANDLE_RETRIEVE_PAYMENT_INTENT'
export const RESET_PAYMENT_STATE = 'payment/RESET_PAYMENT_STATE'
