export const UPDATE_BUY_GOLD_DATA = 'user-finance/UPDATE_GOLD_PURCHASE_DATA'
export const UPDATE_AUTO_INVEST_GOLD_DATA =
  'user-finance/UPDATE_AUTO_INVEST_GOLD_DATA'
export const UPDATE_SELL_GOLD_DATA = 'user-finance/UPDATE_SELL_GOLD_DATA'
export const UPDATE_USER_FINANCE_STATUS =
  'user-finance/UPDATE_USER_FINANCE_STATUS'
export const HANDLE_BUY_GOLD = 'user-finance/HANDLE_BUY_GOLD'
export const HANDLE_AUTO_INVEST_GOLD = 'user-finance/HANDLE_AUTO_INVEST_GOLD'
export const HANDLE_CANCEL_AUTO_INVEST_GOLD =
  'user-finance/HANDLE_CANCEL_AUTO_INVEST_GOLD'
export const HANDLE_SELL_GOLD = 'user-finance/HANDLE_SELL_GOLD'
export const RESET_USER_FINANCE_STATE = 'user-finance/RESET_USER_FINANCE_STATE'
export const HANDLE_USER_INFO = 'user-finance/HANDLE_USER_INFO'
export const HANDLE_USER_BANK_ACCOUNT = 'user-finance/HANDLE_USER_BANK_ACCOUNT'
export const HANDLE_USER_UPI_ID = 'user-finance/HANDLE_USER_UPI_ID'
export const HANDLE_AKAHU_USER_TOKEN_REGISTRATION =
  'user-finance/HANDLE_AKAHU_USER_TOKEN_REGISTRATION'
export const HANDLE_AKAHU_USER_TOKEN_EXCHANGE =
  'user-finance/HANDLE_AKAHU_USER_TOKEN_EXCHANGE'
